### ISSUE TITLE
There is a Stellaris DLC inbound for the 9th. Will this need any changes?

### ISSUE THREAD

**Issue by Sunconure11** [saturnsky/saturn_affinity_python#11]
Just what it says on the tin.

**Comment by saturnsky** [comment]
I'm only focusing on Stellaris because that's what I play, but the program is written in a generic way so it should work for many games. For this reason, it shouldn't be a problem if the version of Stellaris goes up.
It uses the installation path to recognize the program, so if you change the installation path of Stellaris, you'll need to add a new copy of Stellaris with the new path.
